git:
  depth: 3
language: ruby
cache: bundler
branches:
  only:
  - dev
deploy:
  skip_cleanup: true
  provider: script
  script: bin/cideploy
  on:
    branch: dev
env:
  secure: nrqzVUEa6rgZnGligx41chbSOixMgF/XhMgphYCjDpGsqdjlkr1hC6AYYTvTH2CbwnP7+pCCjYAf1+Jdug2730vcAsYE5IESWOVQ2+0q/kULSjLTN/l4cncB8HQ3VSEGR/wl9G52upvvHpHedD2b3inBQ/utuMflfjhf4z8l9AbIr6m3zRtFqWpe8gQVPtALXoNrEXTKg7+7JcPiSoIzENQnGq8SrIjPfeLAR6KBO7hWqTmZh9BKsx03Af5eRc3pUTBlQ62riczsflxF198Waflb7upknVlPCXAo2zFGExV8317zLGdLOI+wRvN9WrFHrkWiVDhaZbU3i5lH+FNWn2Nb6czD3B25h8m84tYriobYlYeNBXvtmq8sulyiFbN32ohdmjSuB6+6S+7EPqdUidY6uTUXdw3p4en4iy6gGGUDdfJosyfqp9ceayj11IAUYVsJBQlmivH0spDLEKgqST5/ilmOhSVEx8ygSTcEtlkZ75DcHBm7uJM+I2HDpp29qPLN35ASTAuX1trNIpr46UxpUgsnhZWQdJd69LahqkOV1NU2+umjoaHdToy3n9igSbqzYWQZkB/OAHZZSI/lBXky0EmTv9z8DyqFY/NytZ192YTv99BV6mv7SQ/5cR8umE8DkXvIXOdCoRz9sE0+qu0ThyRBcVSsGtygKeNcCSg=
