language: ruby
cache: bundler
branches:
  only:
  - dev
deploy:
  skip_cleanup: true
  provider: script
  script: bin/cideploy
  on:
    branch: dev
env:
  secure: 2SEBfgZ+wHJl8sTK2GBplie9nbrVtnOLUlZvek81l7nzMqO15cKggnNoVz/4WJmrvlKQabToISVnWX9VMiKnsuDZ5H2smWF+HF92H6xtrFZw0pNQD7sm6bFvsVPaiwHRigxR6Cs9ATd7BfMGp24mSdxAdlRm3G/pBAkNg94Qyaj3O9tjP6VVUOyglwSWgfFpt8lJsCJ7G2K3IQoocNcCRdxTYUU0/NE+1FbIuhHegxSvZoRnV6zbVHr6UaGR4Sg26CYcjAkCROgJeYcXoZPLfsXPjA5w5YNn0VgqeTjcfwHb41SAxgRpUn8+qGyRhfgBFtdQUecNXf5W/fZJJPuhB54RT/x6e5P8p4l8Y57TXCVQCyDpaaaliNtaM1OBkWPURkLBFNB3ezobyeCcwv69XhnTVJV5LUOH97qnUnYhOftVMspE3lr5MHl3Lc+/qraggRWFV/Z7CHry1UgO4btvk4i1dmV3YODxL9FXhG9J4JWpnuW+uDtYx2tLMTzjwwuwzoxfSQ8b6m1Febl6dffrvoD5h0SlIz/1+PgsImfGFzczhdCpVQlBh25qjL/Rfme7jZZX73I2kMjDL/2o8R3Itp0SOvrMUk8iewqeI0hVZDuFFdpR64S1NvIbAewWfPRxbbIh0coJTO06gkvHbnk7kAfq7AlMuPqjKta0b3cRfZI=
