---
gems:
  - jekyll-bootstrap-sass
  - jekyll-redirect-from
bootstrap:
  assets: true
exclude:
  - .ruby-version
  - .travis.yml
  - bin
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
url: https://klubbdinmamma.com
permalink: pretty
facebook:
  app_id: 251757635194072
  callback_url: http://klubbdinmamma.com
  username: klubbdinmamma
  number_of_photos_to_show_per_album: 10
  exclude_albums_from_download:
    - Cover Photos
    - Mobile Uploads
    - Profile Pictures
    - Timeline Photos
  include_albums_in_html:
    - Simian Ghost (2017)
    - Rein
    - Hanna Järver
    - Boys
    - Laakso
    - Kite
    - Postiljonen
    - Little Jinder
    - Vita Bergen
    - Deportees
    - YAST
    - bob hund
    - Urban Cone
    - The Mary Onettes
    - Vulkano + Taxi Taxi
    - Naomi Pilgrim
    - Solen
    - Dante
    - Zhala
    - Vindvisa
    - jj
    - Colleagues
    - School + Sameblod
    - Nicole Sabouné
    - Simian Ghost
    - Hästpojken
    - Kite (2013)
    - NORDPOLEN säsongspremiär 20/9-13
    - Jens Lekman på Klubb Din Mamma
