---
gems:
  - jekyll-bootstrap-sass
bootstrap:
  assets: true
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
url: http://nya.klubbdinmamma.com
facebook:
  app_id: 251757635194072
  callback_url: http://klubbdinmamma.com
  username: klubbdinmamma
  exclude_albums_from_download:
    - Mobile Uploads
    - Cover Photos
    - Timeline Photos
    - Profile Pictures
  include_albums_in_html:
    - Kite
    - Postiljonen
    - Little Jinder
    - Vita Bergen
    - Deportees
    - YAST
    - bob hund
    - Urban Cone
    - The Mary Onettes
    - Vulkano + Taxi Taxi
    - Naomi Pilgrim
    - Solen
    - Dante
    - Zhala
    - Vindvisa
    - jj
    - Colleagues
